package ui;

import da.DatosAlgoritmos;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import servicios.Conexion;
import servicios.Datos_Servicios;

/**
 *
 * @author Johan Herrera
 */
public class VentanaConsultar extends javax.swing.JFrame {

    /**
     * Creates new form VentanaConsultar
     */
    public VentanaConsultar() {
        initComponents();
        this.setExtendedState(MAXIMIZED_BOTH);
    }
    private final Datos_Servicios datos_servicio = new Datos_Servicios();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tablaDatos = new javax.swing.JTable();
        botonVolver = new javax.swing.JButton();
        botonCargarTodos = new javax.swing.JButton();
        botonEliminarTodo = new javax.swing.JButton();
        botonCargarXDuracion = new javax.swing.JButton();
        botonSalir = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(137, 35));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 28)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Datos Guardados");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 50, -1, -1));

        tablaDatos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tablaDatos.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        tablaDatos.setForeground(new java.awt.Color(0, 0, 0));
        tablaDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID Algoritmo", "Nombre Algoritmo", "Tipo Estructura", "Fecha ", "Duracion (ms)"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tablaDatos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, 700, 430));

        botonVolver.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonVolver.setText("Volver");
        botonVolver.setMaximumSize(new java.awt.Dimension(167, 37));
        botonVolver.setMinimumSize(new java.awt.Dimension(167, 37));
        botonVolver.setPreferredSize(new java.awt.Dimension(167, 37));
        botonVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonVolverActionPerformed(evt);
            }
        });
        getContentPane().add(botonVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 520, 220, 40));

        botonCargarTodos.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonCargarTodos.setText("Cargar Todos");
        botonCargarTodos.setMaximumSize(new java.awt.Dimension(167, 37));
        botonCargarTodos.setMinimumSize(new java.awt.Dimension(167, 37));
        botonCargarTodos.setPreferredSize(new java.awt.Dimension(167, 37));
        botonCargarTodos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarTodosActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarTodos, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 260, 220, 40));

        botonEliminarTodo.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonEliminarTodo.setText("Eliminar datos de la BD");
        botonEliminarTodo.setMaximumSize(new java.awt.Dimension(167, 37));
        botonEliminarTodo.setMinimumSize(new java.awt.Dimension(167, 37));
        botonEliminarTodo.setPreferredSize(new java.awt.Dimension(167, 37));
        botonEliminarTodo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonEliminarTodoActionPerformed(evt);
            }
        });
        getContentPane().add(botonEliminarTodo, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 430, 220, 40));

        botonCargarXDuracion.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonCargarXDuracion.setText("Ordenadar x Duracion");
        botonCargarXDuracion.setMaximumSize(new java.awt.Dimension(167, 37));
        botonCargarXDuracion.setMinimumSize(new java.awt.Dimension(167, 37));
        botonCargarXDuracion.setPreferredSize(new java.awt.Dimension(167, 37));
        botonCargarXDuracion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonCargarXDuracionActionPerformed(evt);
            }
        });
        getContentPane().add(botonCargarXDuracion, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 350, 220, 40));

        botonSalir.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        botonSalir.setText("Salir");
        botonSalir.setMaximumSize(new java.awt.Dimension(167, 37));
        botonSalir.setMinimumSize(new java.awt.Dimension(167, 37));
        botonSalir.setPreferredSize(new java.awt.Dimension(167, 37));
        botonSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botonSalirActionPerformed(evt);
            }
        });
        getContentPane().add(botonSalir, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 610, 220, 40));

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Seleccione la operacion a realizar:");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/Pana Logo ChillTime_opt.jpg"))); // NOI18N
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(1780, 850, -1, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ui/imagenes/fondoPrincipal.jpg"))); // NOI18N
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botonVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonVolverActionPerformed
        this.dispose();
    }//GEN-LAST:event_botonVolverActionPerformed

    private void botonCargarTodosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarTodosActionPerformed
        try {
            List<DatosAlgoritmos> recuperarTodas = this.datos_servicio.recuperarTodas(Conexion.obtener());
            if (recuperarTodas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay datos guardados.");
                return;
            }
            DefaultTableModel modelo = (DefaultTableModel) tablaDatos.getModel();
            Object[] Columna = new Object[modelo.getColumnCount()];
            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            for (int i = 0; i < recuperarTodas.size(); i++) {
                Columna[0] = recuperarTodas.get(i).getId_algoritmo();
                Columna[1] = recuperarTodas.get(i).getNombreAlgoritmo();
                Columna[2] = recuperarTodas.get(i).getTipoEstructura();
                Columna[3] = recuperarTodas.get(i).getFecha();
                Columna[4] = recuperarTodas.get(i).getDuracion();
                modelo.addRow(Columna);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido cargar los registros.");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido cargar los registros.");
        }

    }//GEN-LAST:event_botonCargarTodosActionPerformed

    private void botonCargarXDuracionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonCargarXDuracionActionPerformed
        try {
            List<DatosAlgoritmos> recuperarTodas = this.datos_servicio.recuperarMasRapido(Conexion.obtener());
            if (recuperarTodas.isEmpty()) {
                JOptionPane.showMessageDialog(this, "No hay datos guardados.");
                return;
            }
            DefaultTableModel modelo = (DefaultTableModel) tablaDatos.getModel();
            Object[] Columna = new Object[modelo.getColumnCount()];
            while (modelo.getRowCount() > 0) {
                modelo.removeRow(0);
            }
            for (int i = 0; i < recuperarTodas.size(); i++) {
                Columna[0] = recuperarTodas.get(i).getId_algoritmo();
                Columna[1] = recuperarTodas.get(i).getNombreAlgoritmo();
                Columna[2] = recuperarTodas.get(i).getTipoEstructura();
                Columna[3] = recuperarTodas.get(i).getFecha();
                Columna[4] = recuperarTodas.get(i).getDuracion();
                modelo.addRow(Columna);
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido cargar los registros.");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido cargar los registros.");
        }
    }//GEN-LAST:event_botonCargarXDuracionActionPerformed

    private void botonEliminarTodoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonEliminarTodoActionPerformed
        try {
            this.datos_servicio.eliminar(Conexion.obtener());
            JOptionPane.showMessageDialog(this, "Se han borrado todos los datos de la base de datos exitosamente.");
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido eliminar los registros");
        } catch (ClassNotFoundException ex) {
            System.out.println(ex);
            JOptionPane.showMessageDialog(this, "Ha surgido un error y no se han podido eliminar los registtros");
        }
        DefaultTableModel modelo = (DefaultTableModel) tablaDatos.getModel();
        while (modelo.getRowCount() > 0) {
            modelo.removeRow(0);
        }
    }//GEN-LAST:event_botonEliminarTodoActionPerformed

    private void botonSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botonSalirActionPerformed
        System.exit(0);
    }//GEN-LAST:event_botonSalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaConsultar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new VentanaConsultar().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botonCargarTodos;
    private javax.swing.JButton botonCargarXDuracion;
    private javax.swing.JButton botonEliminarTodo;
    private javax.swing.JButton botonSalir;
    private javax.swing.JButton botonVolver;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tablaDatos;
    // End of variables declaration//GEN-END:variables
}
